local ArcaneDatabase = {
    {
        id = "fireExplosion",
        name = "Explosión de fuego",
        description = "Una pequeña chispa ardiente a un objetivo cercano. En golpe crítico, aplica Incendiado 1 turno.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "conjuration",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "scorch",
        name = "Agostar",
        description = "Un proyectil veloz de fuego puro que impacta al instante. Causa 50% extra de daño si el objetivo está Incendiado.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 0,
        category = "arcane",
        spellType = "fast",
        type = "conjuration",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "fireball",
        name = "Bola de fuego",
        description = "Una bola de fuego ardiente. Aplica el estado Incendiado durante 4 turnos.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 0,
        category = "arcane",
        spellType = "basic",
        type = "conjuration",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "pyroblast",
        name = "Piroexplosión",
        description = "Una deflagración colosal. Empuja a los objetivos y aplica Incendiado durante 6 turnos.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 0,
        category = "arcane",
        spellType = "potent",
        type = "conjuration",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "dragonBreath",
        name = "Aliento de llamas",
        description = "Soplas un pequeño cono de fuego de 2 metros.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "conjuration",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "blastWave",
        name = "Ola explosiva",
        description = "Liberas una onda de calor a tu alrededor que daña a enemigos a corta distancia.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 0,
        category = "arcane",
        spellType = "fast",
        type = "conjuration",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "flamestrike",
        name = "Fogonazo",
        description = "Creas una columna de fuego en un área objetivo de 5 metros.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 0,
        category = "arcane",
        spellType = "basic",
        type = "conjuration",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "meteor",
        name = "Meteoro",
        description = "Haces caer un meteorito llameante que aplasta a los enemigos y deja la zona ardiendo.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 0,
        category = "arcane",
        spellType = "potent",
        type = "conjuration",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "iceLance",
        name = "Lanza de hielo",
        description = "Un fragmento de hielo que entumece al objetivo, reduciendo su velocidad a la mitad (Lentitud).",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "conjuration",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "frostRay",
        name = "Rayo de escarcha",
        description = "Anula el Rango Efectivo de Acción del objetivo temporalmente.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "conjuration",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "frostbolt",
        name = "Descarga de escarcha",
        description = "Un denso proyectil de hielo. Reduce en 1 las acciones del objetivo el próximo turno.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "conjuration",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "glacialSpike",
        name = "Pica glacial",
        description = "Una gigantesca estalactita de hielo. Si el objetivo falla salvación, queda Congelado 1 turno.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "conjuration",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "lesserOrb",
        name = "Orbe menor",
        description = "Una pequeña esfera de escarcha que enfría el entorno a su paso.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "conjuration",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "frostNova",
        name = "Nova de escarcha",
        description = "Congela el suelo alrededor tuya, inmovilizando a enemigos a 3 metros durante 1 turno.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "conjuration",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "coneOfCold",
        name = "Cono de frío",
        description = "Un potente soplo helado en cono frontal que aplica daño y Lentitud.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "conjuration",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "blizzard",
        name = "Ventisca",
        description = "Invoca una feroz tormenta de hielo sobre un área grande, dañando y ralentizando progresivamente.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "conjuration",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = true
    },
    {
        id = "arcaneBarrage",
        name = "Tromba arcana",
        description = "Energía sin refinar que tiene un 25% de probabilidad de ignorar armadura mágica.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "conjuration",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "arcaneMissiles",
        name = "Misiles arcanos",
        description = "Lanzas 3 proyectiles de energía que persiguen a sus objetivos infaliblemente.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "conjuration",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "arcaneStrike",
        name = "Golpe Arcano",
        description = "Una onda inestable de fuerza. Empuja violentamente al objetivo fuera de su Rango Efectivo.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "conjuration",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "arcaneTempest",
        name = "Tempestad Arcana",
        description = "Un rayo cósmico masivo que interrumpe canalizaciones y aplica Silenciado.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "conjuration",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "guidedSpark",
        name = "Chispa guiada",
        description = "Creas una pequeña luz o entidad arcana inofensiva que te sigue o ilumina.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "conjuration",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "conjureRefreshment",
        name = "Conjurar refrigerio",
        description = "Conjuras agua y pan mágicos suficientes para revitalizar a tu grupo fuera de combate.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "conjuration",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "arcaneFamiliar",
        name = "Familiar arcano",
        description = "Invocas un pequeño espíritu arcano que puede lanzar Tromba arcana básica por ti.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 10,
        category = "arcane",
        spellType = "basic",
        type = "conjuration",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "summonWaterElemental",
        name = "Invocar Elemental de Agua",
        description = "Invocas un poderoso Elemental de Agua que obedece tus órdenes en combate.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 10,
        category = "arcane",
        spellType = "potent",
        type = "conjuration",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "fireWard",
        name = "Resguardo de fuego",
        description = "Otorga inmunidad al daño de fuego contra el primer ataque recibido este turno.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "abjuration",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "moltenArmor",
        name = "Armadura de arrabio",
        description = "Protege del fuego y devuelve automáticamente daño de fuego a cualquier atacante cuerpo a cuerpo.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "abjuration",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "flameBarrier",
        name = "Barrera de llamas",
        description = "Mientras esté activa, inflige daño de fuego a enemigos pegados a ti (1-2m).",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "abjuration",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "flameWall",
        name = "Muro de llamas",
        description = "Un inmenso escudo solar que anula por completo el daño físico y de fuego entrante.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "abjuration",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "frostWard",
        name = "Resguardo de escarcha",
        description = "Otorga inmunidad al daño de frío contra el primer ataque recibido este turno.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "abjuration",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "frostArmor",
        name = "Armadura de escarcha",
        description = "Aplica el estado Lentitud a cualquier atacante que te golpee cuerpo a cuerpo.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "abjuration",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "iceBarrier",
        name = "Barrera de hielo",
        description = "Aplica el estado Entumecido (reduce acciones) a los enemigos pegados a ti.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "abjuration",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "iceWall",
        name = "Muro de hielo",
        description = "Bloque de hielo impenetrable que anula daño físico y de frío mientras dure.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "abjuration",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "arcaneWard",
        name = "Resguardo arcano",
        description = "Otorga inmunidad al daño mágico/arcano contra el primer ataque en este turno.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "abjuration",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "arcaneArmor",
        name = "Armadura arcana",
        description = "Empuja mágicamente 2 metros hacia atrás a quien te ataque cuerpo a cuerpo.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "abjuration",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "arcaneBarrier",
        name = "Barrera arcana",
        description = "Aplica el estado Silenciado a los enemigos pegados a ti.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "abjuration",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "arcaneDome",
        name = "Cúpula arcana",
        description = "Un santuario de voluntad. Anula daño físico y mágico por completo.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "abjuration",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "dampenMagic",
        name = "Atenuar magia",
        description = "Reduce ligeramente los efectos mágicos beneficiosos o perjudiciales en el objetivo.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "abjuration",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "contrahechizo",
        name = "Contrahechizo",
        description = "Interrumpe el lanzamiento de un hechizo enemigo si superas una tirada de intelecto.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "abjuration",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "stealSpell",
        name = "Robar hechizo",
        description = "Si superas una tirada de conocimiento arcano, disipas un efecto mágico positivo del enemigo y te lo aplicas a ti.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "abjuration",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "removeCurse",
        name = "Eliminar maldición",
        description = "Disipa inmediatamente los efectos nocivos mágicos severos o maldiciones de un objetivo aliado.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "abjuration",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "magicEye",
        name = "Ojo mágico",
        description = "Tus ojos brillan percibiendo auras mágicas cercanas si no están muy ocultas.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "divination",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "detectMagic",
        name = "Detectar magia",
        description = "Identificas la procedencia, poder y escuela de las auras mágicas presentes en una sala.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "divination",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "seeInvisibility",
        name = "Ver invisibilidad",
        description = "Tus ojos pueden atravesar espectros ilusorios, revelando seres y objetos ocultos.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "divination",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "trueSight",
        name = "Visión verdadera",
        description = "Tu mente se abre a la realidad absoluta, disipando ilusiones, revelando dobles y viendo a través de engaños perfectos.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "divination",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "readMagic",
        name = "Leer magia",
        description = "Permite descifrar runas mágicas básicas o escrituras arcanas simples sin activar sus trampas.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "divination",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "arcaneComprehension",
        name = "Comprensión arcana",
        description = "Tu mente procesa mágicamente el lenguaje, permitiéndote entender y hablar cualquier idioma mundano o mágico.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "divination",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "identificar",
        name = "Identificar",
        description = "Revela inmediatamente las propiedades ocultas, el origen mágico y posibles maldiciones de un objeto tocado.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "divination",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "legendLore",
        name = "Conocimiento de leyendas",
        description = "Invoca el saber ancestral de las líneas ley. Revela la historia profunda y secretos olvidados de un objeto, lugar o persona vital.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "divination",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "arcaneMessage",
        name = "Mensaje arcano",
        description = "Envías un susurro telepático unidireccional a una criatura visible a corta distancia.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "divination",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "readMind",
        name = "Leer la mente",
        description = "Detectas los pensamientos superficiales e intenciones inmediatas de un objetivo si no supera una tirada de voluntad.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "divination",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "clarividencia",
        name = "Clarividencia",
        description = "Proyectas tu consciencia a un punto conocido o a través de los ojos de un aliado, viendo y escuchando lo que allí sucede.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "divination",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "escudrinamiento",
        name = "Escudriñamiento",
        description = "Creas un sensor mágico indetectable que te permite observar a una criatura específica sin importar en qué parte del mundo se encuentre.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "divination",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "arcaneDisguise",
        name = "Disfraz arcano",
        description = "Alteración óptica menor para cambiar los colores de tu ropa, tus rasgos faciales o la voz.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "illusion",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "difuminar",
        name = "Difuminar",
        description = "Tu figura se vuelve borrosa y oscilante, dificultando que los enemigos acierten ataques contra ti.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "illusion",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "invisibilidad",
        name = "Invisibilidad",
        description = "Te desvaneces en el espectro visual. Cualquier acción hostil o mágica romperá el hechizo.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "illusion",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "massInvisibility",
        name = "Invisibilidad en masa",
        description = "Oculta por completo a todos los aliados cercanos. Permite reposicionamientos o huidas perfectas.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "illusion",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "lesserImage",
        name = "Imagen menor",
        description = "Creas una ilusión visual y estática de un objeto pequeño, sin sonido ni tacto, para engañar miradas fugaces.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "illusion",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "exactReflect",
        name = "Reflejo exacto",
        description = "Creas copias ilusorias de ti mismo que imitan tus movimientos, confundiendo a los enemigos a la hora de golpearte.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "illusion",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "astralProjection",
        name = "Proyección astral",
        description = "Proyectas una copia intangible y móvil de ti mismo a gran distancia a la que puedes controlar y usar para hablar.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "illusion",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "mirageArmy",
        name = "Ejército de espejismos",
        description = "Creas docenas de dobles del grupo completo que se mueven de forma errática, sembrando el caos y absorbiendo ataques enemigos.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "illusion",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "phantomSound",
        name = "Sonido fantasma",
        description = "Proyectas voces, pasos o ruidos ilusorios en un punto cercano para distraer guardias o atraer la atención.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "illusion",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "phantomFear",
        name = "Miedo fantasmal",
        description = "El objetivo visualiza su peor miedo. Si falla la salvación, debe huir despavorido de ti.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "illusion",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "illusoryTerrain",
        name = "Terreno ilusorio",
        description = "Alteras la apariencia visual y sonora del terreno, ocultando trampas, fosos o pasadizos bajo falsos suelos y paredes.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "illusion",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "mindPrison",
        name = "Prisión de la mente",
        description = "El objetivo cree estar atrapado en una pesadilla tortuosa infinita. Sufre daño psicosomático y queda incapacitado si no descifra la ilusión.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "illusion",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "innerFire",
        name = "Fuego interno",
        description = "Imbuyes al objetivo con una chispa de fuego, otorgándole resistencia al frío leve o añadiendo 1d4 de daño de fuego a su próximo ataque físico.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "enchantment",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "flameWeapon",
        name = "Arma de llamas",
        description = "Encantas el arma de un aliado. Sus ataques físicos infligen 1d6 de daño de fuego adicional durante la duración.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "enchantment",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "combustion",
        name = "Combustión",
        description = "Enciendes el espíritu del objetivo. Garantiza que sus próximos hechizos o ataques sean golpes críticos y apliquen Incendiado.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "enchantment",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "boundWrath",
        name = "Ira vinculada",
        description = "Encantas a todo el grupo con furia ardiente. Obtienen acciones extra y todos sus ataques explotan en daño de fuego en área.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "enchantment",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "frostMark",
        name = "Marca de escarcha",
        description = "Encantas un objeto o arma para que esté helado al tacto. El próximo golpe con él reduce la velocidad del enemigo.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "enchantment",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "icicles",
        name = "Témpanos de hielo",
        description = "Imbuyes tus piernas con energía gélida estabilizadora, permitiéndote moverte y lanzar hechizos simultáneamente sin penalización.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "enchantment",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "icyVeins",
        name = "Venas heladas",
        description = "Acelera el flujo mágico congelando las distracciones mentales. Ignoras interrupciones al lanzar hechizos durante varios turnos.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "enchantment",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "winterAura",
        name = "Aura de invierno",
        description = "Encantas tu propio cuerpo para irradiar un frío absoluto. Los aliados cercanos ganan armadura de escarcha, y los enemigos sufren Lentitud constante.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "enchantment",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "lesserIntellect",
        name = "Intelecto menor",
        description = "Despiertas ligeramente la mente del objetivo, otorgándole ventaja en su próxima tirada de conocimiento o percepción.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "enchantment",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "arcaneIntellect",
        name = "Intelecto arcano",
        description = "Infunde el cerebro del objetivo con energía arcana, dándole un bono a sus tiradas de intelecto y expandiendo su maná máximo temporalmente.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "enchantment",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "magicFocus",
        name = "Enfoque mágico",
        description = "Vinculas tu mente con la de un aliado. Cuando uno de los dos asesta un golpe crítico, el poder mágico del otro aumenta dramáticamente.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "enchantment",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "touchOfTheMagi",
        name = "Toque de los Magi",
        description = "Encantas maliciosamente a un enemigo. Acumula una porción de todo el daño que reciba y explota tras unos turnos infligiendo ese total como daño Arcano puro.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "enchantment",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "magicSharpening",
        name = "Afiladura mágica",
        description = "Encantas el filo de un arma. Su próximo golpe inflige un leve daño extra por corte perfecto.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "enchantment",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "runicWeapon",
        name = "Arma rúnica",
        description = "El arma cuerpo a cuerpo encantada ignora las armaduras mundanas y su daño se convierte en daño mágico Arcano puro.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "enchantment",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "animatedArmor",
        name = "Armadura animada",
        description = "Encantas la armadura de un aliado para que se mueva por sí sola, bloqueando automáticamente los impactos que el usuario no vería venir.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "enchantment",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "dancingWeapon",
        name = "Arma danzante",
        description = "Encantas un arma para que flote y luche de forma independiente, atacando y flanqueando a los enemigos como si fuese un combatiente más.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "enchantment",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "lesserHex",
        name = "Maleficio menor",
        description = "Cargas a un objetivo con mala suerte arcana, dándole desventaja en su próxima tirada de habilidad o ataque.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "enchantment",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "weightBind",
        name = "Atadura de peso",
        description = "Multiplicas el peso del equipamiento del objetivo. Se mueve a la mitad de su velocidad y no puede realizar evasiones rápidas.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "enchantment",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "forcedSilence",
        name = "Silencio forzado",
        description = "Sellas mágicamente los labios y la garganta del objetivo, incapacitándole por completo para hablar, gritar o lanzar hechizos verbales.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "enchantment",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "outcastMark",
        name = "Marca del paria",
        description = "Maldices al objetivo con una repulsión física. Cualquier aliado suyo que intente acercarse o sanarle será empujado violentamente por el aura de rechazo.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "enchantment",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "lesserRune",
        name = "Runa menor",
        description = "Dibujas una runa lumínica en el suelo. Mientras estés sobre ella, tus ataques arcanos emiten más luz y causan un leve empuje al impactar.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "enchantment",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "containmentRune",
        name = "Runa de contención",
        description = "Encantas una zona pequeña en el suelo. El primer enemigo que la pise detona la trampa, quedando inmovilizado por energía arcana 1 turno.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "enchantment",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "runeOfPower",
        name = "Runa de poder",
        description = "Canalizas un poderoso glifo bajo tus pies (Rune of Power). Mientras permanezcas en su radio, el daño de todos tus hechizos aumenta drásticamente.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "enchantment",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "leylineResonance",
        name = "Resonancia de líneas ley",
        description = "Encantas un área enorme conectándola con las líneas ley. Tú y tus aliados dentro del área recuperáis maná en cada turno y vuestros hechizos no cuestan acciones adicionales.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "enchantment",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "slowFall",
        name = "Caída lenta",
        description = "Alteras la gravedad sobre un aliado o tú mismo, reduciendo la velocidad de caída y previniendo el daño por impacto.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "transmutation",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "traslacion",
        name = "Traslación",
        description = "Pliegas el espacio para teletransportarte instantáneamente 15 metros en la dirección hacia la que miras (Blink).",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "transmutation",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "dimensionalDoor",
        name = "Puerta dimensional",
        description = "Abres un agujero de gusano inestable que te teletransporta a ti y a un objetivo aliado voluntario hasta 50 metros.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "transmutation",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "portal",
        name = "Portal",
        description = "Creas un portal estable hacia una gran ciudad o lugar previamente marcado por ti. Todo el grupo puede cruzarlo.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "transmutation",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "temporalReflexes",
        name = "Reflejos temporales",
        description = "Aceleras tus propios reflejos microsegundos hacia el futuro, previniendo o ignorando un ataque de oportunidad inminente.",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "transmutation",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "ralentizacion",
        name = "Ralentización",
        description = "Vuelves denso el flujo del tiempo alrededor del objetivo. Su velocidad de movimiento se reduce a la mitad y ataca último en su turno.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "transmutation",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "alterTime",
        name = "Alterar tiempo",
        description = "Marcas tu línea temporal (salud y posición actuales). Tras unos turnos o si lo activas de nuevo, retrocedes el tiempo y vuelves a ese estado exacto.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "transmutation",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "timeWarp",
        name = "Distorsión temporal",
        description = "Rasgas el tejido del tiempo (Time Warp) acelerando a todo tu grupo. Ganan acciones extra y máxima velocidad de movimiento temporalmente.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "transmutation",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "materialSleight",
        name = "Prestidigitación material",
        description = "Manipulas temporalmente la materia de un objeto pequeño no mágico (ej: volver líquida una cerradura o ablandar metal).",
        turnCooldown = 1,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        category = "arcane",
        spellType = "cantrip",
        type = "transmutation",
        resourceCost = 0,
        power = 4,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "alterSize",
        name = "Alterar tamaño",
        description = "Transmutas la biología de un aliado o enemigo para hacerlo el doble o la mitad de su tamaño habitual, afectando a su daño físico.",
        turnCooldown = 3,
        costActions = 1,
        costSlots = 1,
        turnEffects = 2,
        category = "arcane",
        spellType = "fast",
        type = "transmutation",
        resourceCost = 3,
        power = 6,
        triggerOpportunityAttack = false,
        isCanalizable = false
    },
    {
        id = "polimorfia",
        name = "Polimorfia",
        description = "Transformas por completo a un humanoide o bestia en una inofensiva oveja. Recibir cualquier tipo de daño revierte la transmutación.",
        turnCooldown = 5,
        costActions = 2,
        costSlots = 2,
        turnEffects = 4,
        category = "arcane",
        spellType = "basic",
        type = "transmutation",
        resourceCost = 6,
        power = 8,
        triggerOpportunityAttack = true,
        isCanalizable = false
    },
    {
        id = "massPolymorph",
        name = "Polimorfia en masa",
        description = "Una inmensa onda de energía transmutadora transforma en ovejas hasta a 5 enemigos en un radio de 10 metros.",
        turnCooldown = 8,
        costActions = 3,
        costSlots = 4,
        turnEffects = 6,
        category = "arcane",
        spellType = "potent",
        type = "transmutation",
        resourceCost = 10,
        power = 10,
        triggerOpportunityAttack = true,
        isCanalizable = false
    }
}

return ArcaneDatabase
