local addonName, GAC = ...

GAC.Actions = {
    UPDATE_PROGRESS = "UPDATE_PROGRESS",
    ADD_EXPERIENCE  = "ADD_EXPERIENCE",
    MODIFY_HEALTH   = "MODIFY_HEALTH",
    MODIFY_SHIELD   = "MODIFY_SHIELD",
    UPDATE_STORY    = "UPDATE_STORY",
}
