type Category = 'noob' | 'normal' | 'elite' | 'boss';

type LevelEntry = {
    maxHealth: number;
    expToLevel: number;
    attPoints: number;
    skillPoints: number;
    heroicPoints: number;
    maxPositiveTraits: number;
};

type LevelTable = {
    [category in Category]: {
        [level: number]: LevelEntry;
    };
};


const levelTable: LevelTable = {
    noob: {
        [1]: {
            maxHealth: 10,
            expToLevel: 10,
            attPoints: 0,
            skillPoints: 2,
            heroicPoints: 1,
            maxPositiveTraits: 0,
        },
        [2]: {
            maxHealth: 11,
            expToLevel: 12,
            attPoints: 1,
            skillPoints: 3,
            heroicPoints: 1,
            maxPositiveTraits: 0,
        },
        [3]: {
            maxHealth: 13,
            expToLevel: 14,
            attPoints: 3,
            skillPoints: 4,
            heroicPoints: 1,
            maxPositiveTraits: 0,
        },
        [4]: {
            maxHealth: 16,
            expToLevel: 16,
            attPoints: 3,
            skillPoints: 5,
            heroicPoints: 1,
            maxPositiveTraits: 0,
        },
        [5]: {
            maxHealth: 20,
            expToLevel: 20,
            attPoints: 5,
            skillPoints: 5,
            heroicPoints: 1,
            maxPositiveTraits: 0,
        },
    },
    normal: {
        [1]: {
            maxHealth: 20,
            expToLevel: 30,
            attPoints: 5,
            skillPoints: 5,
            heroicPoints: 2,
            maxPositiveTraits: 2,
        },
        [2]: {
            maxHealth: 27,
            expToLevel: 45,
            attPoints: 5,
            skillPoints: 6,
            heroicPoints: 2,
            maxPositiveTraits: 2,
        },
        [3]: {
            maxHealth: 34,
            expToLevel: 68,
            attPoints: 6,
            skillPoints: 6,
            heroicPoints: 2,
            maxPositiveTraits: 2,
        },
        [4]: {
            maxHealth: 41,
            expToLevel: 102,
            attPoints: 7,
            skillPoints: 7,
            heroicPoints: 2,
            maxPositiveTraits: 2,
        },
        [5]: {
            maxHealth: 49,
            expToLevel: 153,
            attPoints: 7,
            skillPoints: 7,
            heroicPoints: 3,
            maxPositiveTraits: 2,
        },
        [6]: {
            maxHealth: 57,
            expToLevel: 230,
            attPoints: 8,
            skillPoints: 8,
            heroicPoints: 3,
            maxPositiveTraits: 2,
        },
        [7]: {
            maxHealth: 65,
            expToLevel: 345,
            attPoints: 9,
            skillPoints: 8,
            heroicPoints: 3,
            maxPositiveTraits: 2,
        },
        [8]: {
            maxHealth: 74,
            expToLevel: 518,
            attPoints: 9,
            skillPoints: 9,
            heroicPoints: 3,
            maxPositiveTraits: 2,
        },
        [9]: {
            maxHealth: 83,
            expToLevel: 777,
            attPoints: 10,
            skillPoints: 9,
            heroicPoints: 3,
            maxPositiveTraits: 2,
        },
        [10]: {
            maxHealth: 92,
            expToLevel: 1166,
            attPoints: 10,
            skillPoints: 10,
            heroicPoints: 4,
            maxPositiveTraits: 3,
        },
    },
    elite: {
        [1]: {
            maxHealth: 40,
            expToLevel: 1749,
            attPoints: 10,
            skillPoints: 10,
            heroicPoints: 4,
            maxPositiveTraits: 3,
        },
        [2]: {
            maxHealth: 54,
            expToLevel: 2624,
            attPoints: 11,
            skillPoints: 11,
            heroicPoints: 4,
            maxPositiveTraits: 3,
        },
        [3]: {
            maxHealth: 68,
            expToLevel: 3936,
            attPoints: 12,
            skillPoints: 11,
            heroicPoints: 4,
            maxPositiveTraits: 3,
        },
        [4]: {
            maxHealth: 82,
            expToLevel: 5904,
            attPoints: 13,
            skillPoints: 12,
            heroicPoints: 4,
            maxPositiveTraits: 3,
        },
        [5]: {
            maxHealth: 98,
            expToLevel: 6495,
            attPoints: 13,
            skillPoints: 12,
            heroicPoints: 5,
            maxPositiveTraits: 3,
        },
        [6]: {
            maxHealth: 114,
            expToLevel: 7145,
            attPoints: 14,
            skillPoints: 13,
            heroicPoints: 5,
            maxPositiveTraits: 3,
        },
        [7]: {
            maxHealth: 130,
            expToLevel: 7858,
            attPoints: 14,
            skillPoints: 13,
            heroicPoints: 5,
            maxPositiveTraits: 3,
        },
        [8]: {
            maxHealth: 148,
            expToLevel: 8646,
            attPoints: 14,
            skillPoints: 14,
            heroicPoints: 5,
            maxPositiveTraits: 3,
        },
        [9]: {
            maxHealth: 166,
            expToLevel: 9511,
            attPoints: 15,
            skillPoints: 14,
            heroicPoints: 5,
            maxPositiveTraits: 3,
        },
        [10]: {
            maxHealth: 184,
            expToLevel: 10462,
            attPoints: 15,
            skillPoints: 15,
            heroicPoints: 6,
            maxPositiveTraits: 4,
        },
    },
    boss: {
        [1]: {
            maxHealth: 80,
            expToLevel: 11508,
            attPoints: 15,
            skillPoints: 15,
            heroicPoints: 6,
            maxPositiveTraits: 4,
        },
        [2]: {
            maxHealth: 108,
            expToLevel: 12659,
            attPoints: 16,
            skillPoints: 16,
            heroicPoints: 6,
            maxPositiveTraits: 4,
        },
        [3]: {
            maxHealth: 136,
            expToLevel: 13925,
            attPoints: 17,
            skillPoints: 16,
            heroicPoints: 6,
            maxPositiveTraits: 4,
        },
        [4]: {
            maxHealth: 164,
            expToLevel: 15318,
            attPoints: 18,
            skillPoints: 17,
            heroicPoints: 6,
            maxPositiveTraits: 4,
        },
        [5]: {
            maxHealth: 196,
            expToLevel: 16850,
            attPoints: 18,
            skillPoints: 17,
            heroicPoints: 7,
            maxPositiveTraits: 4,
        },
        [6]: {
            maxHealth: 228,
            expToLevel: 18535,
            attPoints: 19,
            skillPoints: 18,
            heroicPoints: 7,
            maxPositiveTraits: 4,
        },
        [7]: {
            maxHealth: 260,
            expToLevel: 20389,
            attPoints: 19,
            skillPoints: 18,
            heroicPoints: 7,
            maxPositiveTraits: 4,
        },
        [8]: {
            maxHealth: 296,
            expToLevel: 22428,
            attPoints: 19,
            skillPoints: 19,
            heroicPoints: 7,
            maxPositiveTraits: 4,
        },
        [9]: {
            maxHealth: 332,
            expToLevel: 24671,
            attPoints: 20,
            skillPoints: 19,
            heroicPoints: 7,
            maxPositiveTraits: 4,
        },
        [10]: {
            maxHealth: 368,
            expToLevel: -1, // -1 for max level
            attPoints: 20,
            skillPoints: 20,
            heroicPoints: 8,
            maxPositiveTraits: 5,
        },
    },
}
