--- DexteritySkillsDatabase
--- Transpiled skill metadata for dexterity
local DexteritySkillsDatabase = {}

DexteritySkillsDatabase.SkillList = {
    ["esquivar_y_atacar"] = {
        id = "esquivar_y_atacar",
        name = "Esquivar y atacar",
        description = "Después de haber esquivado (defensa ágil) un ataque con éxito puedes atacar sin coste adicional en ese mismo momento.",
        turnCooldown = 3,
        costActions = 0,
        costSlots = 1,
        turnEffects = 0,
        type = "passive",
        category = "dexterity",
    },
    ["golpe_en_puntos_vitales"] = {
        id = "golpe_en_puntos_vitales",
        name = "Golpe en puntos vitales",
        description = "Ataque preciso que perfora zonas críticas. Además del daño del arma, aplica el estado Sangrado continuo. Cuenta como tu ataque del turno.",
        turnCooldown = 2,
        costActions = 2,
        costSlots = 1,
        turnEffects = 3,
        type = "active",
        category = "dexterity",
    },
    ["finta_rapida"] = {
        id = "finta_rapida",
        name = "Finta rápida",
        description = "Engañas visualmente a tu enemigo. Tu próximo ataque obtiene Ventaja automática y el defensor no puede aplicar Defensa Robusta contra él. Este es un caso de habilidad rápida que potencia tu ataque único del turno.",
        turnCooldown = 2,
        costActions = 1,
        costSlots = 1,
        turnEffects = 0,
        type = "active",
        category = "dexterity",
    },
    ["acrobacia_evasiva"] = {
        id = "acrobacia_evasiva",
        name = "Acrobacia evasiva",
        description = "Te mueves 5 metros haciendo piruetas sin provocar ataques de oportunidad y ganas Ventaja en tu próxima Defensa Ágil de este turno.",
        turnCooldown = 2,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        type = "active",
        category = "dexterity",
    },
    ["lluvia_de_cuchillos"] = {
        id = "lluvia_de_cuchillos",
        name = "Lluvia de cuchillos",
        description = "Lanzas armas arrojadizas a hasta 3 objetivos diferentes en un cono frontal cercano. Se salta la regla de 'un solo ataque por turno' a cambio de su alto coste de acciones y enfriamiento.",
        turnCooldown = 3,
        costActions = 2,
        costSlots = 2,
        turnEffects = 0,
        type = "active",
        category = "dexterity",
    },
    ["maestro_de_las_sombras"] = {
        id = "maestro_de_las_sombras",
        name = "Maestro de las sombras",
        description = "Ganas Ventaja permanente en tus tiradas de Sigilo para preparar Emboscadas. Además, si fallas una Emboscada (tirada menor a 10), el enemigo recibe la mitad del daño en lugar de fallar por completo.",
        turnCooldown = 0,
        costActions = 0,
        costSlots = 2,
        turnEffects = 0,
        type = "passive",
        category = "dexterity",
    },
    ["reflejos_felinos"] = {
        id = "reflejos_felinos",
        name = "Reflejos felinos",
        description = "Reduce siempre a la mitad el daño sufrido por caídas. Además, si sufres el estado Derribado, puedes levantarte sin consumir ninguna acción en tu turno.",
        turnCooldown = 0,
        costActions = 0,
        costSlots = 1,
        turnEffects = 0,
        type = "passive",
        category = "dexterity",
    },
    ["tiro_de_gracia"] = {
        id = "tiro_de_gracia",
        name = "Tiro de gracia",
        description = "Si realizas un ataque cuerpo a cuerpo contra un objetivo que sufra el estado Derribado o Aturdido, añades +1D6 al daño total del impacto.",
        turnCooldown = 0,
        costActions = 0,
        costSlots = 1,
        turnEffects = 0,
        type = "passive",
        category = "dexterity",
    },
    ["cortar_tendones"] = {
        id = "cortar_tendones",
        name = "Cortar tendones",
        description = "Un tajo bajo dirigido a las piernas. Aplica el estado Cojera al objetivo. Cuenta como tu ataque del turno.",
        turnCooldown = 3,
        costActions = 2,
        costSlots = 1,
        turnEffects = 2,
        type = "active",
        category = "dexterity",
    },
    ["golpe_bajo_pirata"] = {
        id = "golpe_bajo_pirata",
        name = "Golpe bajo pirata",
        description = "Lucha sucia pura. Aplica el estado Cegado o Aturdido al objetivo si falla su salvación.",
        turnCooldown = 2,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        type = "active",
        category = "dexterity",
    },
    ["disparo_a_quemarropa"] = {
        id = "disparo_a_quemarropa",
        name = "Disparo a quemarropa",
        description = "Al disparar un arma de fuego a rango de cuerpo a cuerpo, evitas desventajas. El impacto empuja al objetivo 2 metros hacia atrás y le aplica el estado Vértigo.",
        turnCooldown = 2,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        type = "active",
        category = "dexterity",
    },
    ["balanceo_de_abordaje"] = {
        id = "balanceo_de_abordaje",
        name = "Balanceo de abordaje",
        description = "Usas una cuerda o liana para balancearte hasta 10 metros volando. Si terminas cayendo sobre un enemigo, puedes realizar una tirada libre para aplicarle el estado Derribado.",
        turnCooldown = 3,
        costActions = 2,
        costSlots = 2,
        turnEffects = 0,
        type = "active",
        category = "dexterity",
    },
    ["apunalamiento_traicionero"] = {
        id = "apunalamiento_traicionero",
        name = "Apuñalamiento traicionero",
        description = "Si atacas a un enemigo flanqueado o por la espalda (donde ya tienes Ventaja), el impacto suma +2D6 adicionales de daño bruto.",
        turnCooldown = 0,
        costActions = 0,
        costSlots = 2,
        turnEffects = 0,
        type = "passive",
        category = "dexterity",
    },
    ["beber_y_pelear"] = {
        id = "beber_y_pelear",
        name = "Beber y pelear",
        description = "Bebes un trago de licor fuerte en combate. Curas una Herida Leve automáticamente y te vuelves inmune al estado Asustado, pero sufres Desventaja en tiradas mentales.",
        turnCooldown = 4,
        costActions = 1,
        costSlots = 1,
        turnEffects = 3,
        type = "active",
        category = "dexterity",
    },
    ["capa_de_duelista"] = {
        id = "capa_de_duelista",
        name = "Capa de duelista",
        description = "Pelear usando una capa o abrigo en tu mano torpe te otorga un +1 pasivo a tu Defensa Ágil, y te permite realizar fintas visuales.",
        turnCooldown = 0,
        costActions = 0,
        costSlots = 1,
        turnEffects = 0,
        type = "passive",
        category = "dexterity",
    },
    ["parada_con_daga_main_gauche"] = {
        id = "parada_con_daga_main_gauche",
        name = "Parada con daga (Main-Gauche)",
        description = "Si luchas empuñando una espada en tu principal y una daga en tu mano torpe, sumas un +2 pasivo a tus tiradas de Defensa Ágil.",
        turnCooldown = 0,
        costActions = 0,
        costSlots = 2,
        turnEffects = 0,
        type = "passive",
        category = "dexterity",
    },
    ["disparo_penetrante"] = {
        id = "disparo_penetrante",
        name = "Disparo Penetrante",
        description = "Utilizas tu extrema precisión para apuntar a los puntos ciegos. Si realizas la acción de 'Disparo de precisión', ignoras por completo los bonificadores otorgados por la Defensa Robusta (escudos o paradas) del objetivo.",
        turnCooldown = 3,
        costActions = 2,
        costSlots = 2,
        turnEffects = 0,
        type = "active",
        category = "dexterity",
    },
    ["disparo_en_movimiento"] = {
        id = "disparo_en_movimiento",
        name = "Disparo en Movimiento",
        description = "Eres un maestro del reposicionamiento ágil. Te permite dividir tu distancia de movimiento gratuito (20m) en dos partes: moverte un poco, realizar tu ataque a distancia, y seguir moviéndote con el resto de la distancia restante.",
        turnCooldown = 2,
        costActions = 1,
        costSlots = 1,
        turnEffects = 0,
        type = "active",
        category = "dexterity",
    },
    ["retirada_tactica"] = {
        id = "retirada_tactica",
        name = "Retirada Táctica",
        description = "Maniobra evasiva veloz. Inmediatamente después de realizar tu ataque a distancia del turno, te desplazas 5 metros hacia atrás en línea recta sin provocar ningún ataque de oportunidad.",
        turnCooldown = 2,
        costActions = 1,
        costSlots = 1,
        turnEffects = 0,
        type = "active",
        category = "dexterity",
    },
    ["ojo_de_halcon"] = {
        id = "ojo_de_halcon",
        name = "Ojo de Halcón",
        description = "Tu dominio visual y talento de Precisión son inigualables. Tu bonificador nativo al usar la acción de 'Disparo de precisión' aumenta a +4 (en lugar del +2 normal) siempre y cuando no te hayas movido en todo el turno.",
        turnCooldown = 0,
        costActions = 0,
        costSlots = 2,
        turnEffects = 0,
        type = "passive",
        category = "dexterity",
    },
    ["apuntar_a_las_piernas"] = {
        id = "apuntar_a_las_piernas",
        name = "Apuntar a las Piernas",
        description = "Disparo de precisión destinado únicamente a incapacitar. Si el ataque impacta, el daño infligido se reduce a la mitad, pero aplicas automáticamente el estado Enraizado al objetivo durante 1 turno.",
        turnCooldown = 3,
        costActions = 2,
        costSlots = 2,
        turnEffects = 1,
        type = "active",
        category = "dexterity",
    },
    ["paso_del_viento"] = {
        id = "paso_del_viento",
        name = "Paso del Viento",
        description = "Te mueves con agilidad extrema, ignorando por completo cualquier penalización o efecto negativo del terreno adverso (como barro, hielo o suelo resbaladizo) al desplazarte durante este turno.",
        turnCooldown = 2,
        costActions = 1,
        costSlots = 1,
        turnEffects = 1,
        type = "active",
        category = "dexterity",
    },
    ["lluvia_de_proyectiles"] = {
        id = "lluvia_de_proyectiles",
        name = "Lluvia de Proyectiles",
        description = "Disparas rápidamente al aire o en abanico frente a ti. Realizas tu ataque del turno afectando a un área de 5 metros de radio a distancia. Los afectados no pueden usar Defensa Robusta, sino que deben realizar una salvación de Defensa Ágil.",
        turnCooldown = 4,
        costActions = 2,
        costSlots = 2,
        turnEffects = 0,
        type = "active",
        category = "dexterity",
    },
}

_G.GAC_DexteritySkillsDatabase = DexteritySkillsDatabase
return DexteritySkillsDatabase
